# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(656, 552)
        self.line_11 = QtWidgets.QFrame(Dialog)
        self.line_11.setGeometry(QtCore.QRect(180, 20, 20, 421))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(190, 180, 391, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_9 = QtWidgets.QFrame(Dialog)
        self.line_9.setGeometry(QtCore.QRect(190, 370, 391, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(200, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setGeometry(QtCore.QRect(190, 320, 391, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(190, 290, 391, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 160, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(190, 90, 391, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(200, 270, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_10 = QtWidgets.QFrame(Dialog)
        self.line_10.setGeometry(QtCore.QRect(340, 20, 20, 431))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_13 = QtWidgets.QFrame(Dialog)
        self.line_13.setGeometry(QtCore.QRect(190, 50, 391, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(200, 290, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_14 = QtWidgets.QFrame(Dialog)
        self.line_14.setGeometry(QtCore.QRect(570, 20, 20, 421))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 470, 251, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setObjectName("pushButton")
        self.line_12 = QtWidgets.QFrame(Dialog)
        self.line_12.setGeometry(QtCore.QRect(190, 400, 391, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_15 = QtWidgets.QFrame(Dialog)
        self.line_15.setGeometry(QtCore.QRect(190, 10, 391, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(200, 200, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(200, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(190, 120, 391, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(200, 330, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(190, 220, 391, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(200, 20, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(190, 150, 391, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(370, 30, 161, 22))
        self.comboBox.setMinimumContentsLength(2)
        self.comboBox.setObjectName("comboBox")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(190, 260, 391, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_humidity = QtWidgets.QLabel(Dialog)
        self.label_humidity.setGeometry(QtCore.QRect(360, 300, 121, 21))
        self.label_humidity.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_humidity.setText("")
        self.label_humidity.setObjectName("label_humidity")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(200, 380, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.line_16 = QtWidgets.QFrame(Dialog)
        self.line_16.setGeometry(QtCore.QRect(190, 440, 391, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(200, 420, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_sunset = QtWidgets.QLabel(Dialog)
        self.label_sunset.setGeometry(QtCore.QRect(360, 420, 161, 20))
        self.label_sunset.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sunset.setText("")
        self.label_sunset.setObjectName("label_sunset")
        self.label_sunrise = QtWidgets.QLabel(Dialog)
        self.label_sunrise.setGeometry(QtCore.QRect(360, 380, 161, 20))
        self.label_sunrise.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sunrise.setText("")
        self.label_sunrise.setObjectName("label_sunrise")
        self.label_windspeed = QtWidgets.QLabel(Dialog)
        self.label_windspeed.setGeometry(QtCore.QRect(360, 340, 151, 20))
        self.label_windspeed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_windspeed.setText("")
        self.label_windspeed.setObjectName("label_windspeed")
        self.label_pressure = QtWidgets.QLabel(Dialog)
        self.label_pressure.setGeometry(QtCore.QRect(360, 270, 101, 20))
        self.label_pressure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_pressure.setText("")
        self.label_pressure.setObjectName("label_pressure")
        self.label_tmpmax = QtWidgets.QLabel(Dialog)
        self.label_tmpmax.setGeometry(QtCore.QRect(360, 240, 101, 20))
        self.label_tmpmax.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_tmpmax.setText("")
        self.label_tmpmax.setObjectName("label_tmpmax")
        self.label_tmpmin = QtWidgets.QLabel(Dialog)
        self.label_tmpmin.setGeometry(QtCore.QRect(360, 200, 101, 20))
        self.label_tmpmin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_tmpmin.setText("")
        self.label_tmpmin.setObjectName("label_tmpmin")
        self.label_temp = QtWidgets.QLabel(Dialog)
        self.label_temp.setGeometry(QtCore.QRect(360, 160, 101, 20))
        self.label_temp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_temp.setText("")
        self.label_temp.setObjectName("label_temp")
        self.label_lat = QtWidgets.QLabel(Dialog)
        self.label_lat.setGeometry(QtCore.QRect(360, 100, 111, 20))
        self.label_lat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_lat.setText("")
        self.label_lat.setObjectName("label_lat")
        self.label_country = QtWidgets.QLabel(Dialog)
        self.label_country.setGeometry(QtCore.QRect(360, 70, 101, 20))
        self.label_country.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_country.setText("")
        self.label_country.setObjectName("label_country")
        self.label_lon = QtWidgets.QLabel(Dialog)
        self.label_lon.setGeometry(QtCore.QRect(360, 130, 101, 20))
        self.label_lon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_lon.setText("")
        self.label_lon.setObjectName("label_lon")

        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "Temperature Max"))
        self.label_3.setText(_translate("Dialog", "Temperature"))
        self.label_4.setText(_translate("Dialog", "Pressure"))
        self.label.setText(_translate("Dialog", "Latitude"))
        self.label_5.setText(_translate("Dialog", "Humidity"))
        self.label_2.setText(_translate("Dialog", "Longitude"))
        self.pushButton.setText(_translate("Dialog", "How is the Climate"))
        self.label_6.setText(_translate("Dialog", "Temperature Min"))
        self.label_8.setText(_translate("Dialog", "Country"))
        self.label_9.setText(_translate("Dialog", "Wind Speed"))
        self.label_12.setText(_translate("Dialog", "City"))
        self.label_22.setText(_translate("Dialog", "SunRise"))
        self.label_23.setText(_translate("Dialog", "SunSet"))


